import { foods } from 'src/app/shared/models/food';
import { Tag } from 'src/app/shared/models/Tag';

export const sample_foods: foods[] = [
      {
      id: '1',
      name: 'Aloo Paratha',
      cookTime: '5-10',
      favorite: true,
      origins: ['India'],
      price: 0.5,
      star: 5.0,
      imageUrl: '/assets/aloo paratha.png',
      tags: ['slowfood','breakfast','lunch','snack'],
    },
    {
      id: '2',
      name:'Burger' ,
      cookTime: '15-20',
      favorite: false,
      origins: ['British'],
      price: 1,
      star: 3.0,
      imageUrl: '/assets/burger.png',
      tags: ['fastfood','snack'],
    },
    {
      id: '3',
      name: 'French Fries',
      cookTime: '30-45',
      favorite: true,
      origins: ['foreign'],
      price: 2,
      star: 2.0,
      imageUrl: '/assets/french fries.png',
      tags: ['fastfood','snack'],
    },
    {
      id: '4',
      name:'Gulab Jamun' ,
      cookTime: '1-2',
      favorite: true,
      origins: ['Pakistan'],
      price: 2,
      star: 5.0,
      imageUrl: '/assets/gulab jamun.png',
      tags: ['sweet','slowfood'],
    },
    {
      id: '5',
      name: 'Idli Sambhar',
      cookTime: '1-2',
      favorite: false,
      origins: ['South-India'],
      price: 1.5,
      star: 4.0,
      imageUrl: '/assets/idli-sambhar.png',
      tags: ['slowfood','healthy','snack','breakfast']
    },
    {
      id: '6',
      name: 'Jalebi',
      cookTime: '30-45',
      favorite: true,
      origins: ['India'],
      price: 1,
      star: 2.0,
      imageUrl: '/assets/jalebi.png',
      tags: ['sweet','slowfood']
    },
    {
      id: '7',
      name: 'Kofta',
      cookTime: '30-45',
      favorite: false,
      origins: ['India'],
      price: 1.5,
      star: 3.0,
      imageUrl: '/assets/kofta.png',
      tags: ['slowfood','Desi','lunch']
    },
    {
      id: '8',
      name: 'Maggi',
      cookTime: '5-10',
      favorite: false,
      origins: ['Japan'],
      price: 0.35,
      star: 4.0,
      imageUrl: '/assets/maggi.png',
      tags: ['fastfood','soup','noodles','snack']
    },
    {
      id: '9',
      name: 'Pizza',
      cookTime: '330-45',
      favorite: false,
      origins: ['foreign'],
      price: 3,
      star: 2.5,
      imageUrl: '/assets/pizza.png',
      tags: ['fastfood','snack']
    },
    {
      id: '10',
      name: 'Puri-sabzi',
      cookTime: '20-30',
      favorite: true,
      origins: ['India'],
      price: 0.75,
      star: 4.5,
      imageUrl: '/assets/puri-sabzi.png',
      tags: ['slowfood','Desi','breakfast']
    },
    {
      id: '11',
      name: 'Samosa',
      cookTime: '45-50',
      favorite: true,
      origins: ['merchants'],
      price: 0.25,
      star: 5.0,
      imageUrl: '/assets/samosa.png',
      tags: ['fastfood','Desi']
    },
    {
      id: '12',
      name: 'Cheesecake',
      cookTime: '50-55',
      favorite: true,
      origins: ['foreign'],
      price: 1.2,
      star: 4.0,
      imageUrl: '/assets/cheesecake.png',
      tags: ['slowfood','sweet'],
    },
    {
      id: '13',
      name: 'Chhole Bhature',
      cookTime: '15-20',
      favorite: true,
      origins: ['India'],
      price: 1,
      star: 5.0,
      imageUrl: '/assets/chhole bhature.png',
      tags: ['breakfast','snack'],
    },
    {
      id: '14',
      name: 'Dahi Bhalla',
      cookTime: '0.5',
      favorite: true,
      origins: ['India'],
      price: 0.5,
      star: 5.0,
      imageUrl: '/assets/dahi bhalla.png',
      tags: ['snack'],
    },
    {
      id: '15',
      name: 'Mango Cheesecake',
      cookTime: '50-55',
      favorite: false,
      origins: ['British'],
      price: 0.5,
      star: 5.0,
      imageUrl: '/assets/mango cheesecake.png',
      tags: ['sweet'],
    },
    {
      id: '16',
      name: 'Raj Kachori',
      cookTime: '30-35',
      favorite: false,
      origins: ['India'],
      price: 0.5,
      star: 5.0,
      imageUrl: '/assets/raj kachori.png',
      tags: ['slowfood','snack'],
    },
    {
      id: '17',
      name: 'Shahi Paneer',
      cookTime: '25-30',
      favorite: false,
      origins: ['India'],
      price: 0.5,
      star: 5.0,
      imageUrl: '/assets/shahi paneer.png',
      tags: ['slowfood','lunch'],
    },
]

export const sample_tags:Tag[] = [
      { name: "All", count: 17},
      { name: 'slowfood', count: 9},
      { name: 'breakfast', count: 4},
      { name: 'lunch', count: 3},
      { name: 'snack', count: 9},
      { name: 'fastfood', count: 5},
      { name: 'sweet', count:4},
      { name: 'Desi', count:3},
      { name: 'noodles', count:1},
      { name: 'soup', count:1},
      { name: 'healthy', count:1},
]